version: 0.2
phases:
   install:
      runtime-versions:
         python: 3.8
      commands:
         - pip install --upgrade pip
   build:
      commands:
         - pip install -r requirements.txt -t .
         - aws lambda update-function-code --function-name ${LAMBDA_FUNCTION_NAME} --zip-file fileb://$(pwd)
artifacts:
   files:
      - '**/*'
